---
# Master playbook - Deploy all infrastructure

- name: Deploy Jenkins Constroller
  import_playbook: deploy_jenkins_controller.yml
  tags: [devsecop, jenkins_controller, jenkins]

- name: Deploy Jenkins Agent
  import_playbook: deploy_jenkins_agent.yml
  tags: [devsecop, jenkins_agent, jenkins]

- name: Deploy SonarQube
  import_playbook: deploy_sonarqube.yml
  tags: [devsecop, sonarqube]

- name: Deploy Artifactory
  import_playbook: deploy_artifactory.yml
  tags: [devsecop, artifactory]
